services:
  demo:
    image: lanthora/candy
    build:
      context: ./
      dockerfile: dockerfile
    network_mode: host
    privileged: true
    devices:
      - /dev/net/tun
    volumes:
      - /var/lib/candy:/var/lib/candy
    restart: always
