services:
  demo:
    image: lanthora/candy
    build:
      context: ./
      dockerfile: dockerfile
    command: -m client -w wss://zone.icandy.one/demo
    network_mode: host
    privileged: true
    devices:
      - /dev/net/tun
    restart: always
