apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: candy-daemonset
spec:
  selector:
    matchLabels:
      app: candy
  template:
    metadata:
      labels:
        app: candy
    spec:
      hostNetwork: true
      containers:
      - name: candy-demo
        image: docker.io/lanthora/candy:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: var-lib-candy
          mountPath: /var/lib/candy
      volumes:
      - name: var-lib-candy
        hostPath:
          path: /var/lib/candy
