version: "3.7"
services:
  candy:
    image: lanthora/candy:latest
    build:
      context: ./
      dockerfile: dockerfile
      tags:
        - lanthora/candy:latest
    container_name: candy
    network_mode: "host"
    privileged: true
    volumes:
      - ./candy.conf:/etc/candy.conf
    devices:
      - /dev/net/tun
    restart: always  
