version: "3.7"
services:
  service:
    build:
      context: ./
      dockerfile: dockerfile
      args:
        # Change to the fastest mirror site for you
        - MIRROR=Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$$repo/os/$$arch
    container_name: candy
    network_mode: "host"
    privileged: true
    volumes:
      - ./candy.conf:/etc/candy.conf
    devices:
      - /dev/net/tun
