name: Check

on:
  pull_request:
    branches: [master]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          check-path: 'src'

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: docker build .

  macos:
    runs-on: macos-13
    steps:
    - name: depends
      run: brew install libconfig spdlog uriparser
    - name: checkout
      uses: actions/checkout@v3
    - name: build
      working-directory: build
      run: |
        export CPATH=/usr/local/include
        export LIBRARY_PATH=/usr/local/lib
        cmake .. && cmake --build .

  windows:
    runs-on: windows-latest
    steps:
    - name: depends
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-libconfig
          mingw-w64-x86_64-spdlog
          mingw-w64-x86_64-uriparser
    - name: checkout
      uses: actions/checkout@v3
    - name: build
      shell: msys2 {0}
      working-directory: build
      run: cmake .. && cmake --build .
