name: Check Code Format

on:
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Check Code Format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          check-path: 'src'
