name: Pull Request Check

on:
  pull_request:
    branches: [master]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: docker build .
